### ISSUE TITLE
Todo list for Bootcamp 202311

### ISSUE THREAD

**Issue by tuhaihe** [cloudberrydb/bootcamp#16]
CloudberryDB Bootcamp is now open source and available for everyone to access. However, there is a lot of work to be done to improve the Bootcamp. The following tasks are required:

- [ ] Add new diagram pictures to the Bootcamp page
- [ ] Integrate the Bootcamp page into the CloudberryDB website
- [ ] Replace "master" with "coordinator" for language inclusivity
